---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      docker:
        patterns:
          - "ghcr.io/duffney/*"
